# Generated by Django 3.2.25 on 2025-09-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=500, null=True)),
                ('user_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mat_staff_no', models.CharField(blank=True, max_length=500, null=True)),
                ('user_dept', models.CharField(blank=True, max_length=500, null=True)),
                ('file_no', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('item_name', models.CharField(max_length=500)),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(max_length=500)),
                ('bal', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_issue', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=500)),
                ('unit_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=15)),
                ('pack_amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=15)),
                ('unit_issue', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=15)),
                ('slug', models.SlugField(blank=True, max_length=2000, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('dept', models.ManyToManyField(related_name='items', to='store.Department')),
            ],
            options={
                'ordering': ['modified_at'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=500, null=True)),
                ('user_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mat_staff_no', models.CharField(blank=True, max_length=500, null=True)),
                ('user_dept', models.CharField(blank=True, max_length=500, null=True)),
                ('file_no', models.CharField(blank=True, max_length=500, null=True)),
                ('item_name', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_issue', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('bal', models.CharField(blank=True, max_length=500, null=True)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.disbursement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.items')),
            ],
        ),
    ]
