# Generated by Django 2.2 on 2023-12-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20231020_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_history_category', to='store.Department'),
        ),
        migrations.AddField(
            model_name='items',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_category', to='store.Department'),
        ),
    ]
