# Generated by Django 2.2 on 2023-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20231205_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='items',
            name='dept',
        ),
        migrations.AddField(
            model_name='items',
            name='dept',
            field=models.ManyToManyField(related_name='items', to='store.Department'),
        ),
    ]
