# Generated by Django 3.2.25 on 2025-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_history_options_alter_items_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=500)),
                ('unit_code', models.CharField(max_length=500)),
            ],
        ),
    ]
