# Generated by Django 3.2.25 on 2025-05-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='pack_amount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=15),
        ),
    ]
