# Generated by Django 3.2.25 on 2025-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20250517_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursement',
            old_name='user',
            new_name='mat_staff_no',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='user_dept',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='user_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='user_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
