# Generated by Django 3.2.25 on 2025-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20250517_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementitem',
            name='unit_issue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
