# Generated by Django 3.2.25 on 2025-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_disbursementitem_unit_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AddField(
            model_name='disbursement',
            name='file_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
