# Generated by Django 3.2.25 on 2025-05-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20250518_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementitem',
            name='disbursement',
        ),
        migrations.RemoveField(
            model_name='disbursementitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Disbursement',
        ),
        migrations.DeleteModel(
            name='DisbursementItem',
        ),
    ]
