# Generated by Django 3.2.25 on 2025-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_disbursement_disbursementitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('item_name', models.CharField(max_length=500)),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(max_length=500)),
                ('bal', models.CharField(blank=True, max_length=500, null=True)),
                ('unit_issue', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
