# Generated by Django 3.2.25 on 2025-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_supplyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementitem',
            name='dateCreated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='disbursementitem',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
