# Generated by Django 3.2.25 on 2025-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20250518_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementitem',
            name='bal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
