# Generated by Django 3.2.25 on 2025-05-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_disbursementitem_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementitem',
            name='file_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disbursementitem',
            name='mat_staff_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disbursementitem',
            name='user_dept',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disbursementitem',
            name='user_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='disbursementitem',
            name='user_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
