# Generated by Django 3.2.25 on 2025-05-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20250518_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursementitem',
            old_name='unit_price',
            new_name='unit_rate',
        ),
    ]
