# Generated by Django 3.2.25 on 2025-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_unit_price_disbursementitem_unit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
