# Generated by Django 3.2.25 on 2025-09-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='jamb_no',
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff')], default=1, max_length=15),
        ),
    ]
