# Generated by Django 3.2.25 on 2025-09-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20250923_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='matric_no',
            new_name='id_no',
        ),
    ]
